# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion-cli" do
  version "0.1.29"

  on_macos do
    on_intel do
      sha256 "087b2dfee42a313e16e819d1b4f02bda1573375f65b341c5ca557a7dfdf6c2dc"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cbcfcc71a8ea41e4ae97403e3c00dfc0d3e4d08bf4f315238f42c1b20d790b4"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5df44ecd627dc32c814c58c8f562c5b8055a4650a246ad7f62579797f5ab0775"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "504002bce28be1c03c630a1f770d7339d30e796cca197675268cebff06354cee"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_linux_arm64.tar.gz"
    end
  end

  name "orion-cli"
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  # No zap stanza required

end
