# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion-cli" do
  version "0.1.21"

  on_macos do
    on_intel do
      sha256 "658d80656a05f822e9d0469bbca15c1671db706c8e63aed43bbb781f6df05114"
      url "https://github.com/Perseusoft/orion-releases/releases/download/v#{version}/orion-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cffbdc99c8a9f6732291976a7570c00693376cc712e247432e2044f44f0a5e3e"
      url "https://github.com/Perseusoft/orion-releases/releases/download/v#{version}/orion-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5488755824938b9bddb3d21bb2e649cefe374b778dad119cb34868285c3c8821"
      url "https://github.com/Perseusoft/orion-releases/releases/download/v#{version}/orion-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e696d384b3f3be537a94d90a29d6f7e1477b09df5e3fadba4fd0aae55dc9105"
      url "https://github.com/Perseusoft/orion-releases/releases/download/v#{version}/orion-cli_linux_arm64.tar.gz"
    end
  end

  name "orion-cli"
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  # No zap stanza required

end
