# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion-cli" do
  version "0.1.26"

  on_macos do
    on_intel do
      sha256 "ee040a7ff2f25c3709b424685b9d76f22331202d33542e819b82e13b1ab360f3"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09c028a0ab99ac94dd5090b0d6f51ed4da91494929a81c44ba6485f78fe8dfba"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5dcf2567461240960971af0bc6e1a361a6749c71cf13c8cb45a07206ba3d6b7b"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9b34af8b31fccb6a71f327f4475b453a56a50c134e5edbb22bd64fd73c7d1ef"
      url "https://dl.orionops.tech/cli/releases/v#{version}/orion-cli_linux_arm64.tar.gz"
    end
  end

  name "orion-cli"
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  # No zap stanza required

end
