# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrionCli < Formula
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"
  version "0.1.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.5/orion-cli_darwin_amd64.tar.gz"
      sha256 "41b7d73b45636cea4fdc7e73cd4a59cecae432ad052833b56b69b114ffb42272"

      def install
        bin.install "orion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.5/orion-cli_darwin_arm64.tar.gz"
      sha256 "4f14782fff00838b44915696ba3493b186581ed3265107add14f16ec2337aa33"

      def install
        bin.install "orion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.5/orion-cli_linux_amd64.tar.gz"
        sha256 "f7cc653623754633b6455433a630c47445d852ed2a0ef0f300c7e1c65ce6d96d"

        def install
          bin.install "orion"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.5/orion-cli_linux_arm64.tar.gz"
        sha256 "0e99a8a13aafe134465cd7160d3ddc2368a18c2d87dc987db9351e5ff7444347"

        def install
          bin.install "orion"
        end
      end
    end
  end

  test do
    system "#{bin}/orion", "version"
  end
end
