# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrionCli < Formula
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"
  version "0.1.13"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.13/orion-cli_darwin_amd64.tar.gz"
      sha256 "2881df0a9683cb4dcacc9a94a6333b5ddba1a43f4330e68c61bbce617bf5c92c"

      def install
        bin.install "orion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.13/orion-cli_darwin_arm64.tar.gz"
      sha256 "641f536b6a453c97dac146f975f291d2087a683afa2eca338a582d3ff0f1c672"

      def install
        bin.install "orion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.13/orion-cli_linux_amd64.tar.gz"
        sha256 "623378f2a527ca1853e8add6eb8327001f3cd6280261b726537d4082f72e4c71"

        def install
          bin.install "orion"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.13/orion-cli_linux_arm64.tar.gz"
        sha256 "0264e935e297b6866ec376f3a458412b3ccdd772ff5a12c2ca1768c12edd5a98"

        def install
          bin.install "orion"
        end
      end
    end
  end

  test do
    system "#{bin}/orion", "version"
  end
end
