# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrionCli < Formula
  desc "OrionOps CLI — Specialized AI agents for code generation"
  homepage "https://orionops.tech"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.1/orion-cli_darwin_amd64.tar.gz"
      sha256 "055f291cb375213aee492ac6768a00eb3bfc1f389b60cdd24e7591bbd03e6173"

      def install
        bin.install "orion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.1/orion-cli_darwin_arm64.tar.gz"
      sha256 "3b0f8e761c0ec81b33cd6225a912097355851f53a5c1723d583d3588157f8d9f"

      def install
        bin.install "orion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.1/orion-cli_linux_amd64.tar.gz"
        sha256 "390eed6e8f03814fbb89588ba4f44dd4a3cbea0cf650ed7f60a196387c2d2d69"

        def install
          bin.install "orion"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Perseusoft/orion-releases/releases/download/v0.1.1/orion-cli_linux_arm64.tar.gz"
        sha256 "03fd8637ce08ed561df38920b6c512e0f2c020c446d3926d78fc1886f9e976b4"

        def install
          bin.install "orion"
        end
      end
    end
  end

  test do
    system "#{bin}/orion", "version"
  end
end
